name: PR-AFFAIRE
favicon: null
layout_spectrum: 0.58474
typography_spectrum: 0.8988367421552539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cb726e'
    - '#522539'
    - '#80384c'
    - '#eeb298'
    - '#040821'
  brandStrength: 0.39859860111027956
  lightness: 0.6873004878871143
  saturation: 0.8951002655085176
  rhythmicContrast: 0.277641513152048
purpose: []
